# Generated by Django 3.2.9 on 2021-11-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_order_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
