# Generated by Django 3.2.9 on 2021-11-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_used',
            field=models.BooleanField(default=False),
        ),
    ]
