# Generated by Django 3.2.9 on 2021-11-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_idpay_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='idpay_track_id',
            field=models.IntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
