# Generated by Django 3.2.9 on 2021-11-17 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_discount_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='discount_used',
        ),
    ]
