# Generated by Django 3.2.9 on 2021-11-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_idpay_track_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='idpay_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='idpay_track_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
