# Generated by Django 3.2.9 on 2021-12-22 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211222_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variation_choices',
            field=models.ManyToManyField(blank=True, null=True, to='shop.VariationChoice'),
        ),
    ]
