# Generated by Django 3.2.9 on 2021-11-18 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211118_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationchoice',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation_choices', to='shop.variation'),
        ),
    ]
