# Generated by Django 3.2.9 on 2021-12-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_orderitem_variation_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='variation_choices',
            field=models.ManyToManyField(blank=True, to='shop.VariationChoice'),
        ),
    ]
