# Generated by Django 3.2.9 on 2021-12-23 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_auto_20211222_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='date_expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
