# Generated by Django 3.2.9 on 2021-11-18 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_variationchoice_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variationchoice',
            name='variation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.variation'),
        ),
    ]
