# Generated by Django 3.2.9 on 2021-12-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phoneotp',
            old_name='counter',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='verfied',
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
