# Generated by Django 3.2.9 on 2021-12-22 07:55

from django.db import migrations, models
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211221_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(max_length=11, unique=True, validators=[user.validators.phone_validator]),
        ),
    ]
