# Generated by Django 3.2.9 on 2021-12-26 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_doublepay_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doublepay',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhoneOtp',
        ),
        migrations.DeleteModel(
            name='DoublePay',
        ),
    ]
